### PR TITLE
Use findall instead of iter and iterfind in the enable-centos.py script

### PR DESCRIPTION
**Pull request by mpreisler**
This makes the script work on Pythons older than 2.7.

### CODE REVIEW

**Comment by shawndwells** [comment]
Using Python 2.6.6 (aka RHEL6) I was able to duplicate the errors:
`````
$ pwd
/var/www/html/scap-security-guide

$ make rhel5
.....
../../shared/utils/enable-centos.py output/ssg-rhel5-xccdf.xml output/ssg-centos5-xccdf.xml
Traceback (most recent call last):
  File "../../shared/utils/enable-centos.py", line 170, in <module>
    main()
  File "../../shared/utils/enable-centos.py", line 148, in main
    for elem in list(tree.iter("{%s}Benchmark" % (XCCDF11_NS)))
AttributeError: ElementTree instance has no attribute 'iter'
make[1]: *** [content] Error 1
make[1]: Leaving directory `/var/www/html/scap-security-guide/RHEL/5'
make: *** [rhel5] Error 2
`````

After patch:
`````
$ git checkout -b mpreisler-centos_support master
$ git pull https://github.com/mpreisler/scap-security-guide.git centos_support
$ make rhel5
......
(successful build)
````
